parserOptions:
  ecmaVersion: 6

env:
  node: true

plugins:
  - prettier

extends:
  - plugin:prettier/recommended

rules:
  prettier/prettier: ["error", { "singleQuote": true }]

overrides:
  - files: "test/**/*.js"
    env:
      mocha: true
